'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';

import {
  BarChart3,
  CheckCircle2,
  Target,
  AlertTriangle,
  Brain,
  TrendingUp,
  ChevronRight,
  GraduationCap,
  Users,
  Activity,
  Shield,
  Zap,
  Star,
  Award,
  Sparkles
} from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { MagicCard } from '@/components/ui/MagicCard';
import { GlowButton } from '@/components/ui/GlowButton';
import { ParticleBackground } from '@/components/ui/ParticleBackground';
import { ThemeToggle } from '@/components/ui/ThemeToggle';
import { AnimatedBackground } from '@/components/ui/AnimatedBackground';
import { FloatingOrbs } from '@/components/ui/FloatingOrbs';
import { GlassCard } from '@/components/ui/GlassCard';

export default function LandingPage() {

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.3
      }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { duration: 0.5, ease: "easeOut" } }
  };

  const features = [
    {
      icon: BarChart3,
      title: "Performance Tracking",
      desc: "Real-time analytics for quizzes, exams, and assignments with trend visualization.",
      color: "text-blue-500",
      bg: "bg-blue-500/10"
    },
    {
      icon: CheckCircle2,
      title: "Smart Attendance",
      desc: "Automated attendance tracking with QR integration and trend reporting.",
      color: "text-emerald-500",
      bg: "bg-emerald-500/10"
    },
    {
      icon: Brain,
      title: "AI Study Plans",
      desc: "Personalized 7-day learning roadmaps generated by AI based on your goals.",
      color: "text-purple-500",
      bg: "bg-purple-500/10"
    },
    {
      icon: AlertTriangle,
      title: "Risk Prevention",
      desc: "Advanced prediction models that flag students requiring early intervention.",
      color: "text-amber-500",
      bg: "bg-amber-500/10"
    },
    {
      icon: Target,
      title: "Skill Gap Analysis",
      desc: "Identify strengths and weaknesses across core and elective subjects automatically.",
      color: "text-rose-500",
      bg: "bg-rose-500/10"
    },
    {
      icon: TrendingUp,
      title: "Progress Visualization",
      desc: "Stunning heatmaps and spider charts showing multidimensional progress over time.",
      color: "text-indigo-500",
      bg: "bg-indigo-500/10"
    }
  ];

  return (
    <div className="relative min-h-screen bg-background dark:bg-gradient-to-br dark:from-slate-950 dark:via-slate-900 dark:to-slate-950 transition-colors duration-500 overflow-x-hidden">
      <AnimatedBackground />
      <FloatingOrbs />
      <ParticleBackground />

      {/* Navbar */}
      <nav className="fixed top-0 w-full z-50 bg-white/50 dark:bg-slate-950/50 backdrop-blur-xl border-b border-slate-200 dark:border-slate-800">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="flex items-center gap-3"
          >
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-blue-600 to-purple-600 flex items-center justify-center shadow-lg shadow-blue-500/20">
              <GraduationCap className="text-white w-6 h-6" />
            </div>
            <span className="font-bold text-xl tracking-tight bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              EduTrack
            </span>
          </motion.div>

          <div className="flex items-center gap-6">
            <div className="hidden md:flex items-center gap-8 text-sm font-medium text-slate-600 dark:text-slate-400">
              <Link href="#features" className="hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Features</Link>
              <Link href="#about" className="hover:text-blue-600 dark:hover:text-blue-400 transition-colors">About</Link>
              <Link href="#contact" className="hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Contact</Link>
            </div>
            <div className="h-6 w-[1px] bg-slate-200 dark:bg-slate-800 hidden md:block"></div>
            <ThemeToggle />
            <Link href="/auth/login" className="hidden sm:block">
              <Button variant="ghost" className="font-semibold px-6">Login</Button>
            </Link>
            <Link href="/auth/register">
              <GlowButton className="text-sm px-6 py-2.5 rounded-xl">Get Started</GlowButton>
            </Link>
          </div>
        </div>
      </nav>

      <main className="relative pt-32 pb-20 px-6">
        {/* Hero Section */}
        <section className="max-w-7xl mx-auto text-center mb-32">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-50 dark:bg-blue-900/30 border border-blue-100 dark:border-blue-800 text-blue-600 dark:text-blue-400 text-sm font-bold mb-8 shadow-sm"
          >
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
            </span>
            Next-Gen Academic Intelligence
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.1 }}
            className="text-6xl md:text-8xl font-black tracking-tight mb-8 leading-[1.1] dark:text-white"
          >
            Master Your Learning <br />
            <span className="bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent">
              With AI Precision
            </span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.2 }}
            className="text-xl md:text-2xl text-slate-500 dark:text-slate-400 max-w-3xl mx-auto mb-12 leading-relaxed"
          >
            The all-in-one platform for schools to track performance, predict academic risks,
            and generate personalized AI learning roadmaps for every student.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-6"
          >
            <Link href="/auth/register">
              <GlowButton className="text-lg px-10 py-5 rounded-2xl">
                Start Free Trial <ChevronRight className="w-5 h-5" />
              </GlowButton>
            </Link>
            <Link href="#features">
              <Button variant="outline" className="text-lg px-10 py-7 rounded-2xl bg-white/50 dark:bg-slate-900/50 backdrop-blur-md border-slate-200 dark:border-slate-800">
                View Features
              </Button>
            </Link>
          </motion.div>

          {/* Advanced Dashboard Preview */}
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.5 }}
            className="mt-24 relative max-w-6xl mx-auto"
          >
            <div className="absolute -inset-8 bg-gradient-to-tr from-blue-600/20 via-purple-600/20 to-pink-600/20 blur-3xl -z-10 rounded-3xl" />

            {/* Main showcase container with glassmorphism */}
            <div className="relative">
              {/* Floating Feature Cards */}
              <div className="grid md:grid-cols-3 gap-6 px-4">

                {/* CARD 1 — Blue */}
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.6 }}
                  whileHover={{ y: -10, scale: 1.02 }}
                  className="md:translate-y-8"
                >
                  <GlassCard
                    className="
          relative p-8 group cursor-pointer
          bg-white/90 dark:bg-slate-900/80
          border border-blue-200/60 dark:border-blue-500/30
          shadow-xl shadow-blue-500/10
          backdrop-blur-xl
        "
                  >
                    <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-transparent via-blue-500/60 to-transparent" />

                    <div className="relative z-10">
                      <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center mb-4 shadow-lg shadow-blue-500/40">
                        <BarChart3 className="w-7 h-7 text-white" />
                      </div>

                      <h3 className="text-xl font-extrabold mb-2 text-slate-900 dark:text-slate-100">
                        Real-Time Analytics
                      </h3>

                      <p className="text-slate-700 dark:text-slate-300 text-sm">
                        Track performance with live dashboards and insights
                      </p>

                      <div className="mt-4 pt-4 border-t border-slate-200/70 dark:border-slate-700/50">
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-slate-600 dark:text-slate-400">Accuracy</span>
                          <span className="font-bold text-blue-600 dark:text-blue-400">98%</span>
                        </div>
                      </div>
                    </div>
                  </GlassCard>
                </motion.div>

                {/* CARD 2 — Purple */}
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.7 }}
                  whileHover={{ y: -10, scale: 1.02 }}
                >
                  <GlassCard
                    className="
          relative p-8 group cursor-pointer
          bg-white/90 dark:bg-slate-900/80
          border border-purple-200/60 dark:border-purple-500/30
          shadow-xl shadow-purple-500/10
          backdrop-blur-xl
        "
                  >
                    <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-transparent via-purple-500/60 to-transparent" />

                    <div className="relative z-10">
                      <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center mb-4 shadow-lg shadow-purple-500/40">
                        <Brain className="w-7 h-7 text-white" />
                      </div>

                      <h3 className="text-xl font-extrabold mb-2 text-slate-900 dark:text-slate-100">
                        AI-Powered Insights
                      </h3>

                      <p className="text-slate-700 dark:text-slate-300 text-sm">
                        Personalized learning paths generated by AI
                      </p>

                      <div className="mt-4 pt-4 border-t border-slate-200/70 dark:border-slate-700/50">
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-slate-600 dark:text-slate-400">Satisfaction</span>
                          <span className="font-bold text-purple-600 dark:text-purple-400">95%</span>
                        </div>
                      </div>
                    </div>
                  </GlassCard>
                </motion.div>

                {/* CARD 3 — Emerald */}
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.8 }}
                  whileHover={{ y: -10, scale: 1.02 }}
                  className="md:translate-y-8"
                >
                  <GlassCard
                    className="
          relative p-8 group cursor-pointer
          bg-white/90 dark:bg-slate-900/80
          border border-emerald-200/60 dark:border-emerald-500/30
          shadow-xl shadow-emerald-500/10
          backdrop-blur-xl
        "
                  >
                    <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-transparent via-emerald-500/60 to-transparent" />

                    <div className="relative z-10">
                      <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center mb-4 shadow-lg shadow-emerald-500/40">
                        <Sparkles className="w-7 h-7 text-white" />
                      </div>

                      <h3 className="text-xl font-extrabold mb-2 text-slate-900 dark:text-slate-100">
                        Smart Predictions
                      </h3>

                      <p className="text-slate-700 dark:text-slate-300 text-sm">
                        Early intervention with risk prediction models
                      </p>

                      <div className="mt-4 pt-4 border-t border-slate-200/70 dark:border-slate-700/50">
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-slate-600 dark:text-slate-400">Precision</span>
                          <span className="font-bold text-emerald-600 dark:text-emerald-400">92%</span>
                        </div>
                      </div>
                    </div>
                  </GlassCard>
                </motion.div>
              </div>

              {/* Central Achievement Badge */}
              <motion.div
                initial={{ opacity: 0, scale: 0.5 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.9, type: "spring" }}
                className="absolute -bottom-8 left-1/2 -translate-x-1/2 z-20"
              >
                <div className="relative">
                  <div className="absolute inset-0 bg-gradient-to-br from-yellow-400 to-orange-500 blur-2xl opacity-60 rounded-full" />
                  <div className="relative w-24 h-24 rounded-full bg-gradient-to-br from-yellow-400 to-orange-500 flex items-center justify-center shadow-2xl border-4 border-white dark:border-slate-900">
                    <Award className="w-12 h-12 text-white" />
                  </div>
                </div>
              </motion.div>
            </div>

          </motion.div>
        </section>

        {/* Features Section */}
        <section id="features" className="max-w-7xl mx-auto py-20">
          <div className="text-center mb-20">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="text-4xl md:text-5xl font-black mb-6 dark:text-white"
            >
              Powerful AI-Driven Features
            </motion.h2>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="text-lg text-slate-500 dark:text-slate-400 max-w-2xl mx-auto"
            >
              Everything you need to manage academic excellence in one place.
            </motion.p>
          </div>

          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="grid md:grid-cols-2 lg:grid-cols-3 gap-8"
          >
            {features.map((feature, i) => (
              <MagicCard
                key={i}
                gradient
                className="
    h-full rounded-[2rem] overflow-hidden
    bg-white/95           /* 🔥 STRONGER light bg */
    dark:bg-slate-900/50
    backdrop-blur-md
    border border-slate-300/70   /* 🔥 clearer border in light */
    dark:border-slate-700/40
    shadow-xl shadow-slate-300/40 /* 🔥 visible light shadow */
    dark:shadow-slate-950/30
  "
              >
                {/* IMPORTANT: z-10 so content stays above gradient */}
                <div className="relative z-10 p-8 md:p-10 flex flex-col h-full">

                  {/* Icon */}
                  <div
                    className={`
        w-14 h-14 rounded-2xl
        ${feature.bg}
        flex items-center justify-center mb-8
        shadow-md
        relative overflow-hidden
        group-hover:scale-110 transition-transform duration-300
      `}
                  >
                    <div
                      className={`
          absolute inset-0
          ${feature.bg}
          blur-xl opacity-0
          group-hover:opacity-60 transition-opacity duration-500
        `}
                    />
                    <feature.icon className={`w-7 h-7 ${feature.color} relative z-10`} />
                  </div>

                  {/* Title */}
                  <h3 className="
      text-2xl font-extrabold mb-4
      text-slate-900        /* 🔥 darker title in light */
      dark:text-slate-50
    ">
                    {feature.title}
                  </h3>

                  {/* Description */}
                  <p className="
      text-slate-800        /* 🔥 stronger body text */
      dark:text-slate-300
      leading-relaxed mb-8 flex-grow
    ">
                    {feature.desc}
                  </p>

                  {/* Learn more */}
                  <div className="
      mt-auto flex items-center text-sm font-bold
      text-blue-800         /* 🔥 clearer CTA in light */
      dark:text-blue-400
      group/link cursor-pointer
    ">
                    Learn more
                    <ChevronRight className="w-4 h-4 ml-1 group-hover/link:translate-x-1 transition-transform" />
                  </div>
                </div>
              </MagicCard>

            ))}
          </motion.div>
        </section>

        {/* Stats Section */}
        <section className="max-w-7xl mx-auto py-20 px-6">
          <div className="bg-gradient-to-br from-blue-600 to-indigo-700 dark:from-blue-900 dark:to-indigo-900 rounded-[3rem] p-12 md:p-20 text-white relative overflow-hidden shadow-2xl shadow-blue-500/20">
            {/* Decorative circles */}
            <div className="absolute top-0 right-0 w-96 h-96 bg-white/10 rounded-full -translate-y-1/2 translate-x-1/3 blur-3xl pointer-events-none" />
            <div className="absolute bottom-0 left-0 w-64 h-64 bg-purple-500/20 rounded-full translate-y-1/2 -translate-x-1/4 blur-3xl pointer-events-none" />

            <div className="grid md:grid-cols-2 gap-12 items-center relative z-10">
              <div>
                <h2 className="text-4xl md:text-5xl font-black mb-8 leading-tight">
                  Trusted by Forward-Thinking Institutions
                </h2>
                <p className="text-xl text-blue-100 mb-10 leading-relaxed">
                  Empowering educators with data-driven insights to transform the student learning experience.
                </p>
                <div className="grid grid-cols-2 gap-8">
                  <div>
                    <div className="text-4xl font-black mb-2">98%</div>
                    <div className="text-blue-200 text-sm font-medium uppercase tracking-wider">Teacher Satisfaction</div>
                  </div>
                  <div>
                    <div className="text-4xl font-black mb-2">45%</div>
                    <div className="text-blue-200 text-sm font-medium uppercase tracking-wider">Better Risk Prediction</div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <div className="bg-white/10 backdrop-blur-md rounded-3xl p-6 border border-white/10">
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-12 h-12 rounded-full bg-blue-400 flex items-center justify-center">
                      <Users className="w-6 h-6 text-white" />
                    </div>
                    <div>
                      <div className="font-bold">12,000+</div>
                      <div className="text-xs text-blue-200">Active Students</div>
                    </div>
                  </div>
                  <div className="h-2 w-full bg-white/10 rounded-full overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      whileInView={{ width: '85%' }}
                      transition={{ duration: 1.5, ease: "easeOut" }}
                      className="h-full bg-white"
                    />
                  </div>
                </div>
                <div className="bg-white/10 backdrop-blur-md rounded-3xl p-6 border border-white/10 translate-x-4 md:translate-x-8">
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-12 h-12 rounded-full bg-indigo-400 flex items-center justify-center">
                      <Activity className="w-6 h-6 text-white" />
                    </div>
                    <div>
                      <div className="font-bold">5,000+</div>
                      <div className="text-xs text-blue-200">Reports Generated</div>
                    </div>
                  </div>
                  <div className="h-2 w-full bg-white/10 rounded-full overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      whileInView={{ width: '92%' }}
                      transition={{ duration: 1.5, ease: "easeOut", delay: 0.2 }}
                      className="h-full bg-white"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="max-w-7xl mx-auto py-32 text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-5xl md:text-6xl font-black mb-8 dark:text-white">
              Ready to Elevate <br />
              <span className="bg-gradient-to-r from-blue-600 to-purple-600 dark:from-blue-400 dark:to-purple-400 bg-clip-text text-transparent">
                Your Institution?
              </span>
            </h2>
            <p className="text-xl text-slate-500 dark:text-slate-400 max-w-2xl mx-auto mb-12">
              Join the ranks of elite educational institutions using EduTrack to drive student success.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link href="/auth/register">
                <GlowButton className="text-lg px-12 py-6 rounded-2xl">
                  Get Started Free
                </GlowButton>
              </Link>
              <Button variant="ghost" className="text-lg px-12 py-6 rounded-2xl group">
                Talk to Sales <ChevronRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
              </Button>
            </div>
          </motion.div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-white dark:bg-slate-950 border-t border-slate-200 dark:border-slate-800 pt-20 pb-10 px-6 relative z-10">
        <div className="max-w-7xl mx-auto grid md:grid-cols-4 gap-12 mb-20">
          <div className="col-span-1 md:col-span-1">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-blue-600 to-purple-600 flex items-center justify-center shadow-lg shadow-blue-500/20">
                <GraduationCap className="text-white w-5 h-5" />
              </div>
              <span className="font-bold text-lg tracking-tight bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                EduTrack
              </span>
            </div>
            <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">
              Driving educational excellence through advanced AI analytics and personalized learning pathways.
            </p>
          </div>

          <div>
            <h4 className="font-bold mb-6 dark:text-slate-100">Platform</h4>
            <ul className="space-y-4 text-sm text-slate-500 dark:text-slate-400">
              <li className="hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer transition-colors">Performance Analytics</li>
              <li className="hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer transition-colors">AI Learning Roadmaps</li>
              <li className="hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer transition-colors">Risk Prediction</li>
              <li className="hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer transition-colors">Attendance Tracking</li>
            </ul>
          </div>

          <div>
            <h4 className="font-bold mb-6 dark:text-slate-100">Company</h4>
            <ul className="space-y-4 text-sm text-slate-500 dark:text-slate-400">
              <li className="hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer transition-colors">About Us</li>
              <li className="hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer transition-colors">Case Studies</li>
              <li className="hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer transition-colors">Careers</li>
              <li className="hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer transition-colors">Privacy Policy</li>
            </ul>
          </div>

          <div>
            <h4 className="font-bold mb-6 dark:text-slate-100">Connect</h4>
            <div className="flex gap-4">
              <div className="w-10 h-10 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center hover:bg-blue-600 hover:text-white transition-all cursor-pointer">
                <Users className="w-5 h-5" />
              </div>
              <div className="w-10 h-10 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center hover:bg-blue-600 hover:text-white transition-all cursor-pointer">
                <Shield className="w-5 h-5" />
              </div>
              <div className="w-10 h-10 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center hover:bg-blue-600 hover:text-white transition-all cursor-pointer">
                <Activity className="w-5 h-5" />
              </div>
            </div>
          </div>
        </div>

        <div className="max-w-7xl mx-auto pt-10 border-t border-slate-200 dark:border-slate-800 flex flex-col md:flex-row justify-between items-center gap-6">
          <p className="text-sm text-slate-500 dark:text-slate-400">
            © 2025 EduTrack. All rights reserved.
          </p>
          <div className="flex gap-8 text-xs font-bold text-slate-400 uppercase tracking-widest">
            <span className="hover:text-blue-600 cursor-pointer transition-colors">Status</span>
            <span className="hover:text-blue-600 cursor-pointer transition-colors">Security</span>
            <span className="hover:text-blue-600 cursor-pointer transition-colors">Cookies</span>
          </div>
        </div>
      </footer>
    </div>
  );
}